# Generated by Django 5.0.6 on 2024-05-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorinterest',
            name='amount_offered',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Amount offered for investment', max_digits=10),
        ),
        migrations.AddField(
            model_name='investorinterest',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=10.5, help_text='interest rate for the amount offered', max_digits=5),
        ),
    ]
